Transform: AWS::Serverless-2016-10-31

Globals:
    Function:
        Runtime: python3.8
        Timeout: 180
Resources:
    NewGameFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: MafiaNewGame
            Runtime: python3.8
            CodeUri: ./
            Handler: mafiaNewGame.lambda_handler
            Events:
                NewGame:
                    Type: Api 
                    Properties:
                        Path: /newgame/{game_id}
                        Method: get
    UpdateGameFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: MafiaUpdateGame
            Runtime: python3.8
            CodeUri: ./
            Handler: mafiaUpdateGame.lambda_handler
            Events:
                NewGame:
                    Type: Api 
                    Properties:
                        Path: /updategame/{game_id}/{action}/{player_id}
                        Method: get
    GameStateTable:
        Type: AWS::Serverless::SimpleTable
        Properties:
            PrimaryKey: 
                Name: _id
                Type: String
            TableName: gameState
